openapi: 3.0.0
info: 
  title: STD24189
  description: This is a specification of STD24189
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /ping:
    get:
      summary: retourne pong
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
  /cars:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  identifier :
                    type: string
                  brand: 
                    type: string
                  model: 
                    type: string
                
                    

    get:
      summary: retourne liste
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/Car'
components:
  schemas:
    Car:
      type: object
      properties:
        identifier :
          type: string
        brand: 
          type: string
        model: 
          type: string  
